[FEATURE] deploy and setup scripts

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,34 +1,53 @@
-#!/usr/bin/env ruby
-require 'pathname'
-require 'fileutils'
-include FileUtils
+#!/bin/sh
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
+# Set up Rails app. Run this script immediately after cloning the codebase.
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+# Exit if any subcommand fails
+set -e
 
-chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file.
+# Set up Ruby dependencies via Bundler
+echo "== Installing dependencies =="
+gem install bundler --conservative
+bundle check || bundle install
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+# Some gem dependecies we can take care of with brew
+if [[ $OSTYPE == darwin* ]]; then
+  brew update
+  which -s postgres || brew install postgres
+fi
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   cp 'config/database.yml.sample', 'config/database.yml'
-  # end
+if ! which -s postgres; then
+  echo "You must install postgres onto this system"
+fi
 
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:setup'
+# Set up database and add any development seed data
+echo "\n== Preparing database =="
+bin/rake dev:prime
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
+# Clean out any old log/tmp files
+echo "\n== Removing old logs and tempfiles =="
+bin/rails log:clear tmp:clear
 
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
+mkdir -p .git/safe
+
+echo "\n== Heroku and git setup =="
+if heroku join --app iexpedition-staging > /dev/null 2>&1; then
+  git remote add staging git@heroku.com:iexpedition-staging.git || true
+  printf "You are a collaborator on the 'iexpedition-staging' Heroku app
+"
+else
+  printf "Ask for access to the iexpedition heroku team and the 'iexpedition-staging' Heroku app
+"
+fi
+
+if heroku join --app iexpedition-production > /dev/null 2>&1; then
+  git remote add production git@heroku.com:iexpedition-production.git || true
+  printf "You are a collaborator on the 'iexpedition-production' Heroku app
+"
+else
+  printf "Ask for access to the iexpedition heroku team and the 'iexpedition-production' Heroku app
+"
+fi
+
+git config heroku.remote staging
